#pragma once

/* Handedness. */
// #define MASTER_LEFT
#define EE_HANDS

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

/* RGB matrix support. */
#ifdef RGB_MATRIX_ENABLE
    #define SPLIT_TRANSPORT_MIRROR
    #define RGB_MATRIX_LED_COUNT 42
    #define RGB_MATRIX_SPLIT { 21, 21 }
    #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 100
    #define RGB_MATRIX_DEFAULT_VAL 100
    #define RGB_MATRIX_SLEEP

    #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
    // #define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
    // #define ENABLE_RGB_MATRIX_DUAL_BEACON
    // #define ENABLE_RGB_MATRIX_RAINBOW_BEACON
    // #define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
    // #define ENABLE_RGB_MATRIX_HUE_PENDULUM

    #define RGB_MATRIX_KEYPRESSES // reacts to keypresses
    #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
    // #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
    // #define ENABLE_RGB_MATRIX_SPLASH
    // #define ENABLE_RGB_MATRIX_SOLID_SPLASH
#endif
